export const SPECIALITIES = [
	{
		en_name: "Urology",
		fr_name: "Urologie",
		ar_name: "طب المسالك البولية",
		slug: "urology",
	},
	{
		en_name: "Dentistry",
		fr_name: "Dentisterie",
		ar_name: "طب الأسنان",
		slug: "dentistry",
	},
	{
		en_name: "Rheumatology",
		fr_name: "Rhumatologie",
		ar_name: "طب الروماتيزم",
		slug: "rheumatology",
	},
	{
		en_name: "Psychiatry",
		fr_name: "Psychiatrie",
		ar_name: "الطب النفسي",
		slug: "psychiatry",
	},
	{
		en_name: "Pulmonology",
		fr_name: "Pneumologie",
		ar_name: "طب أمراض الرئة",
		slug: "pulmonology",
	},
	{
		en_name: "Pediatrics",
		fr_name: "Pediatrie",
		ar_name: "طب الأطفال",
		slug: "pediatrics",
	},
	{
		en_name: "Ophthalmology",
		fr_name: "Ophtalmologie",
		ar_name: "طب العيون",
		slug: "ophthalmology",
	},
	{
		en_name: "Otorhinolaryngology (ENT)",
		fr_name: "O R L",
		ar_name: "طب الأنف والأذن والحنجرة",
		slug: "otorhinolaryngology",
	},
	{
		en_name: "Nutrition",
		fr_name: "Nutrition",
		ar_name: "التغذية",
		slug: "nutrition",
	},
	{
		en_name: "General Practice",
		fr_name: "Médecine générale",
		ar_name: "الطب العام",
		slug: "general_practice",
	},
	{
		en_name: "Neurology",
		fr_name: "Neurologie",
		ar_name: "طب الأعصاب",
		slug: "neurology",
	},
	{
		en_name: "Neurosurgery",
		fr_name: "Neuro-chirurgie",
		ar_name: "جراحة الأعصاب",
		slug: "neurosurgery",
	},
	{
		en_name: "Nephrology",
		fr_name: "Nephrologie",
		ar_name: "طب الكلى",
		slug: "nephrology",
	},
	{
		en_name: "Physical Medicine and Rehabilitation",
		fr_name: "Medecine Physique",
		ar_name: "الطب الفيزيائي وإعادة التأهيل",
		slug: "physical_medicine_and_rehabilitation",
	},
	{
		en_name: "Internal Medicine",
		fr_name: "Medecine Interne",
		ar_name: "الطب الباطني",
		slug: "internal_medicine",
	},
	{
		en_name: "Infectious Diseases",
		fr_name: "Maladies Infectieuses",
		ar_name: "الأمراض المعدية",
		slug: "infectious_diseases",
	},
	{
		en_name: "Hematology",
		fr_name: "Hematologie",
		ar_name: "أمراض الدم",
		slug: "hematology",
	},
	{
		en_name: "Obstetrics and Gynecology",
		fr_name: "Gynecologie-obstetrique",
		ar_name: "طب النساء والتوليد",
		slug: "obstetrics_and_gynecology",
	},
	{
		en_name: "Gastroenterology",
		fr_name: "Gastrologie",
		ar_name: "طب الجهاز الهضمي",
		slug: "gastroenterology",
	},
	{
		en_name: "Endocrinology",
		fr_name: "Endocrinologie",
		ar_name: "طب الغدد الصماء",
		slug: "endocrinology",
	},
	{
		en_name: "Dermatology",
		fr_name: "Dermatologie",
		ar_name: "الأمراض الجلدية",
		slug: "dermatology",
	},
	{
		en_name: "Plastic Surgery",
		fr_name: "Chirurgie Plastique",
		ar_name: "جراحة التجميل",
		slug: "plastic_surgery",
	},
	{
		en_name: "Orthopedic Surgery",
		fr_name: "Chirurgie Orthopedique",
		ar_name: "جراحة العظام",
		slug: "orthopedic_surgery",
	},
	{
		en_name: "Maxillofacial Surgery",
		fr_name: "Chirurgie Maxillo-faciale",
		ar_name: "جراحة الوجه والفكين",
		slug: "maxillofacial_surgery",
	},
	{
		en_name: "Pediatric Surgery",
		fr_name: "Chirurgie Infantile",
		ar_name: "جراحة الأطفال",
		slug: "pediatric_surgery",
	},
	{
		en_name: "General Surgery",
		fr_name: "Chirurgie Generale",
		ar_name: "الجراحة العامة",
		slug: "general_surgery",
	},
	{
		en_name: "Cardiovascular and Thoracic Surgery",
		fr_name: "Chi. Cardiovasculaire T",
		ar_name: "جراحة القلب والأوعية الدموية والصدر",
		slug: "cardiovascular_and_thoracic_surgery",
	},
	{
		en_name: "Cardiology",
		fr_name: "Cardiologie",
		ar_name: "أمراض القلب",
		slug: "cardiology",
	},
	{
		en_name: "Physiotherapy & Kinesitherapy",
		fr_name: "Physiotherapie et kinesitherapie",
		ar_name: "العلاج الطبيعي والحركات العلاجية",
		slug: "physiotherapy",
	},
	{
		en_name: "Psychology",
		fr_name: "Psychologie",
		ar_name: "علم النفس",
		slug: "psychology",
	},
	{
		en_name: "Allergology",
		fr_name: "Allergologie",
		ar_name: "أمراض الحساسية",
		slug: "allergology",
	},
	{
		en_name: "Vascular Medicine & Angiology",
		fr_name: "Medecine vasculaire et angiologie",
		ar_name: "طب الأوعية الدموية",
		slug: "vascular_medicine",
	},
	{
		en_name: "Diabetology",
		fr_name: "Diabetologie",
		ar_name: "طب السكري",
		slug: "diabetology",
	},
];
