export const SPECIALITIES = [
	{
		id: 1,
		en_name: "Urology",
		fr_name: "Urologie",
		ar_name: "طب المسالك البولية",
		slug: "urology",
	},
	{
		id: 2,
		en_name: "Stomatology",
		fr_name: "Stomatologie",
		ar_name: "طب الفم",
		slug: "stomatology",
	},
	{
		id: 3,
		en_name: "Rheumatology",
		fr_name: "Rhumatologie",
		ar_name: "طب الروماتيزم",
		slug: "rheumatology",
	},
	{
		id: 4,
		en_name: "Radiology",
		fr_name: "Radiologie",
		ar_name: "الأشعة",
		slug: "radiology",
	},
	{
		id: 5,
		en_name: "Psychiatry",
		fr_name: "Psychiatrie",
		ar_name: "الطب النفسي",
		slug: "psychiatry",
	},
	{
		id: 6,
		en_name: "Pulmonology",
		fr_name: "Pneumologie",
		ar_name: "طب أمراض الرئة",
		slug: "pulmonology",
	},
	{
		id: 7,
		en_name: "Pediatrics",
		fr_name: "Pediatrie",
		ar_name: "طب الأطفال",
		slug: "pediatrics",
	},
	{
		id: 8,
		en_name: "Parasitology",
		fr_name: "Parasitologie",
		ar_name: "علم الطفيليات",
		slug: "parasitology",
	},
	{
		id: 9,
		en_name: "Ophthalmology",
		fr_name: "Ophtalmologie",
		ar_name: "طب العيون",
		slug: "ophthalmology",
	},
	{
		id: 10,
		en_name: "Radiation Oncology",
		fr_name: "Radiotherapie",
		ar_name: "العلاج الإشعاعي",
		slug: "radiation_oncology",
	},
	{
		id: 11,
		en_name: "Otorhinolaryngology (ENT)",
		fr_name: "O R L",
		ar_name: "طب الأنف والأذن والحنجرة",
		slug: "otorhinolaryngology",
	},
	{
		id: 12,
		en_name: "Nutrition",
		fr_name: "Nutrition",
		ar_name: "التغذية",
		slug: "nutrition",
	},
	{
		id: 13,
		en_name: "Unclassified",
		fr_name: "Non Classe",
		ar_name: "غير مصنف",
		slug: "unclassified",
	},
	{
		id: 14,
		en_name: "Neurology",
		fr_name: "Neurologie",
		ar_name: "طب الأعصاب",
		slug: "neurology",
	},
	{
		id: 15,
		en_name: "Neurosurgery",
		fr_name: "Neuro-chirurgie",
		ar_name: "جراحة الأعصاب",
		slug: "neurosurgery",
	},
	{
		id: 16,
		en_name: "Nephrology",
		fr_name: "Nephrologie",
		ar_name: "طب الكلى",
		slug: "nephrology",
	},
	{
		id: 17,
		en_name: "Physical Medicine and Rehabilitation",
		fr_name: "Medecine Physique",
		ar_name: "الطب الفيزيائي وإعادة التأهيل",
		slug: "physical_medicine_and_rehabilitation",
	},
	{
		id: 18,
		en_name: "Forensic Medicine",
		fr_name: "Medecine Legale",
		ar_name: "الطب الشرعي",
		slug: "forensic_medicine",
	},
	{
		id: 19,
		en_name: "Internal Medicine",
		fr_name: "Medecine Interne",
		ar_name: "الطب الباطني",
		slug: "internal_medicine",
	},
	{
		id: 20,
		en_name: "Infectious Diseases",
		fr_name: "Maladies Infectieuses",
		ar_name: "الأمراض المعدية",
		slug: "infectious_diseases",
	},
	{
		id: 21,
		en_name: "Hematology",
		fr_name: "Hematologie",
		ar_name: "أمراض الدم",
		slug: "hematology",
	},
	{
		id: 22,
		en_name: "Obstetrics and Gynecology",
		fr_name: "Gynecologie-obstetrique",
		ar_name: "طب النساء والتوليد",
		slug: "obstetrics_and_gynecology",
	},
	{
		id: 23,
		en_name: "Gastroenterology",
		fr_name: "Gastrologie",
		ar_name: "طب الجهاز الهضمي",
		slug: "gastroenterology",
	},
	{
		id: 24,
		en_name: "Nuclear Medicine",
		fr_name: "Medecine Nucleaire",
		ar_name: "الطب النووي",
		slug: "nuclear_medicine",
	},
	{
		id: 25,
		en_name: "Histology and Embryology",
		fr_name: "Histologie Embryologie",
		ar_name: "علم الأنسجة والأجنة",
		slug: "histology_and_embryology",
	},
	{
		id: 26,
		en_name: "Neurosurgeon",
		fr_name: "Neurochirurgien",
		ar_name: "جرّاح أعصاب",
		slug: "neurosurgeon",
	},
	{
		id: 27,
		en_name: "Endocrinology",
		fr_name: "Endocrinologie",
		ar_name: "طب الغدد الصماء",
		slug: "endocrinology",
	},
	{
		id: 28,
		en_name: "Dermatology",
		fr_name: "Dermatologie",
		ar_name: "الأمراض الجلدية",
		slug: "dermatology",
	},
	{
		id: 29,
		en_name: "Plastic Surgery",
		fr_name: "Chirurgie Plastique",
		ar_name: "جراحة التجميل",
		slug: "plastic_surgery",
	},
	{
		id: 30,
		en_name: "Orthopedic Surgery",
		fr_name: "Chirurgie Orthopedique",
		ar_name: "جراحة العظام",
		slug: "orthopedic_surgery",
	},
	{
		id: 31,
		en_name: "Maxillofacial Surgery",
		fr_name: "Chirurgie Maxillo-faciale",
		ar_name: "جراحة الوجه والفكين",
		slug: "maxillofacial_surgery",
	},
	{
		id: 32,
		en_name: "Pediatric Surgery",
		fr_name: "Chirurgie Infantile",
		ar_name: "جراحة الأطفال",
		slug: "pediatric_surgery",
	},
	{
		id: 33,
		en_name: "General Surgery",
		fr_name: "Chirurgie Generale",
		ar_name: "الجراحة العامة",
		slug: "general_surgery",
	},
	{
		id: 34,
		en_name: "Cardiovascular and Thoracic Surgery",
		fr_name: "Chi. Cardiovasculaire T",
		ar_name: "جراحة القلب والأوعية الدموية والصدر",
		slug: "cardiovascular_and_thoracic_surgery",
	},
	{
		id: 35,
		en_name: "Cardiology",
		fr_name: "Cardiologie",
		ar_name: "أمراض القلب",
		slug: "cardiology",
	},
	{
		id: 36,
		en_name: "Medical Oncology",
		fr_name: "Carcinologie Medicale",
		ar_name: "طب الأورام",
		slug: "medical_oncology",
	},
	{
		id: 37,
		en_name: "Clinical Biology",
		fr_name: "Biologie Clinique",
		ar_name: "البيولوجيا السريرية",
		slug: "clinical_biology",
	},
	{
		id: 38,
		en_name: "Anesthesiology and Intensive Care",
		fr_name: "Anesthesie-reanimation",
		ar_name: "التخدير والإنعاش",
		slug: "anesthesiology_and_intensive_care",
	},
	{
		id: 39,
		en_name: "Anatomical Pathology",
		fr_name: "Anatomie-pathologie",
		ar_name: "علم الأمراض التشريحي",
		slug: "anatomical_pathology",
	},
	{
		id: 40,
		en_name: "Surgical Oncology",
		fr_name: "Chirurgie Carcinologie",
		ar_name: "جراحة الأورام",
		slug: "surgical_oncology",
	},
];
