export const SPECIALITIES = [
	{
		enName: "Urology",
		frName: "Urologie",
		arName: "طب المسالك البولية",
		slug: "urology",
	},
	{
		enName: "Stomatology",
		frName: "Stomatologie",
		arName: "طب الفم",
		slug: "stomatology",
	},
	{
		enName: "Rheumatology",
		frName: "Rhumatologie",
		arName: "طب الروماتيزم",
		slug: "rheumatology",
	},
	{
		enName: "Radiology",
		frName: "Radiologie",
		arName: "الأشعة",
		slug: "radiology",
	},
	{
		enName: "Psychiatry",
		frName: "Psychiatrie",
		arName: "الطب النفسي",
		slug: "psychiatry",
	},
	{
		enName: "Pulmonology",
		frName: "Pneumologie",
		arName: "طب أمراض الرئة",
		slug: "pulmonology",
	},
	{
		enName: "Pediatrics",
		frName: "Pediatrie",
		arName: "طب الأطفال",
		slug: "pediatrics",
	},
	{
		enName: "Parasitology",
		frName: "Parasitologie",
		arName: "علم الطفيليات",
		slug: "parasitology",
	},
	{
		enName: "Ophthalmology",
		frName: "Ophtalmologie",
		arName: "طب العيون",
		slug: "ophthalmology",
	},
	{
		enName: "Radiation Oncology",
		frName: "Radiotherapie",
		arName: "العلاج الإشعاعي",
		slug: "radiation_oncology",
	},
	{
		enName: "Otorhinolaryngology (ENT)",
		frName: "O R L",
		arName: "طب الأنف والأذن والحنجرة",
		slug: "otorhinolaryngology",
	},
	{
		enName: "Nutrition",
		frName: "Nutrition",
		arName: "التغذية",
		slug: "nutrition",
	},
	{
		enName: "Unclassified",
		frName: "Non Classe",
		arName: "غير مصنف",
		slug: "unclassified",
	},
	{
		enName: "Neurology",
		frName: "Neurologie",
		arName: "طب الأعصاب",
		slug: "neurology",
	},
	{
		enName: "Neurosurgery",
		frName: "Neuro-chirurgie",
		arName: "جراحة الأعصاب",
		slug: "neurosurgery",
	},
	{
		enName: "Nephrology",
		frName: "Nephrologie",
		arName: "طب الكلى",
		slug: "nephrology",
	},
	{
		enName: "Physical Medicine and Rehabilitation",
		frName: "Medecine Physique",
		arName: "الطب الفيزيائي وإعادة التأهيل",
		slug: "physical_medicine_and_rehabilitation",
	},
	{
		enName: "Forensic Medicine",
		frName: "Medecine Legale",
		arName: "الطب الشرعي",
		slug: "forensic_medicine",
	},
	{
		enName: "Internal Medicine",
		frName: "Medecine Interne",
		arName: "الطب الباطني",
		slug: "internal_medicine",
	},
	{
		enName: "Infectious Diseases",
		frName: "Maladies Infectieuses",
		arName: "الأمراض المعدية",
		slug: "infectious_diseases",
	},
	{
		enName: "Hematology",
		frName: "Hematologie",
		arName: "أمراض الدم",
		slug: "hematology",
	},
	{
		enName: "Obstetrics and Gynecology",
		frName: "Gynecologie-obstetrique",
		arName: "طب النساء والتوليد",
		slug: "obstetrics_and_gynecology",
	},
	{
		enName: "Gastroenterology",
		frName: "Gastrologie",
		arName: "طب الجهاز الهضمي",
		slug: "gastroenterology",
	},
	{
		enName: "Nuclear Medicine",
		frName: "Medecine Nucleaire",
		arName: "الطب النووي",
		slug: "nuclear_medicine",
	},
	{
		enName: "Histology and Embryology",
		frName: "Histologie Embryologie",
		arName: "علم الأنسجة والأجنة",
		slug: "histology_and_embryology",
	},
	{
		enName: "Neurosurgeon",
		frName: "Neurochirurgien",
		arName: "جرّاح أعصاب",
		slug: "neurosurgeon",
	},
	{
		enName: "Endocrinology",
		frName: "Endocrinologie",
		arName: "طب الغدد الصماء",
		slug: "endocrinology",
	},
	{
		enName: "Dermatology",
		frName: "Dermatologie",
		arName: "الأمراض الجلدية",
		slug: "dermatology",
	},
	{
		enName: "Plastic Surgery",
		frName: "Chirurgie Plastique",
		arName: "جراحة التجميل",
		slug: "plastic_surgery",
	},
	{
		enName: "Orthopedic Surgery",
		frName: "Chirurgie Orthopedique",
		arName: "جراحة العظام",
		slug: "orthopedic_surgery",
	},
	{
		enName: "Maxillofacial Surgery",
		frName: "Chirurgie Maxillo-faciale",
		arName: "جراحة الوجه والفكين",
		slug: "maxillofacial_surgery",
	},
	{
		enName: "Pediatric Surgery",
		frName: "Chirurgie Infantile",
		arName: "جراحة الأطفال",
		slug: "pediatric_surgery",
	},
	{
		enName: "General Surgery",
		frName: "Chirurgie Generale",
		arName: "الجراحة العامة",
		slug: "general_surgery",
	},
	{
		enName: "Cardiovascular and Thoracic Surgery",
		frName: "Chi. Cardiovasculaire T",
		arName: "جراحة القلب والأوعية الدموية والصدر",
		slug: "cardiovascular_and_thoracic_surgery",
	},
	{
		enName: "Cardiology",
		frName: "Cardiologie",
		arName: "أمراض القلب",
		slug: "cardiology",
	},
	{
		enName: "Medical Oncology",
		frName: "Carcinologie Medicale",
		arName: "طب الأورام",
		slug: "medical_oncology",
	},
	{
		enName: "Clinical Biology",
		frName: "Biologie Clinique",
		arName: "البيولوجيا السريرية",
		slug: "clinical_biology",
	},
	{
		enName: "Anesthesiology and Intensive Care",
		frName: "Anesthesie-reanimation",
		arName: "التخدير والإنعاش",
		slug: "anesthesiology_and_intensive_care",
	},
	{
		enName: "Anatomical Pathology",
		frName: "Anatomie-pathologie",
		arName: "علم الأمراض التشريحي",
		slug: "anatomical_pathology",
	},
	{
		enName: "Surgical Oncology",
		frName: "Chirurgie Carcinologie",
		arName: "جراحة الأورام",
		slug: "surgical_oncology",
	},
];
