export const SPECIALITIES = [
	{
		enName: "Urology",
		frName: "Urologie",
		arName: "طب المسالك البولية",
		slug: "urology",
	},
	{
		enName: "Dentistry",
		frName: "Dentisterie",
		arName: "طب الأسنان",
		slug: "dentistry",
	},
	{
		enName: "Rheumatology",
		frName: "Rhumatologie",
		arName: "طب الروماتيزم",
		slug: "rheumatology",
	},
	{
		enName: "Psychiatry",
		frName: "Psychiatrie",
		arName: "الطب النفسي",
		slug: "psychiatry",
	},
	{
		enName: "Pulmonology",
		frName: "Pneumologie",
		arName: "طب أمراض الرئة",
		slug: "pulmonology",
	},
	{
		enName: "Pediatrics",
		frName: "Pediatrie",
		arName: "طب الأطفال",
		slug: "pediatrics",
	},
	{
		enName: "Ophthalmology",
		frName: "Ophtalmologie",
		arName: "طب العيون",
		slug: "ophthalmology",
	},
	{
		enName: "Otorhinolaryngology (ENT)",
		frName: "O R L",
		arName: "طب الأنف والأذن والحنجرة",
		slug: "otorhinolaryngology",
	},
	{
		enName: "Nutrition",
		frName: "Nutrition",
		arName: "التغذية",
		slug: "nutrition",
	},
	{
		enName: "General Practice",
		frName: "Médecine générale",
		arName: "الطب العام",
		slug: "general_practice",
	},
	{
		enName: "Neurology",
		frName: "Neurologie",
		arName: "طب الأعصاب",
		slug: "neurology",
	},
	{
		enName: "Neurosurgery",
		frName: "Neuro-chirurgie",
		arName: "جراحة الأعصاب",
		slug: "neurosurgery",
	},
	{
		enName: "Nephrology",
		frName: "Nephrologie",
		arName: "طب الكلى",
		slug: "nephrology",
	},
	{
		enName: "Physical Medicine and Rehabilitation",
		frName: "Medecine Physique",
		arName: "الطب الفيزيائي وإعادة التأهيل",
		slug: "physical_medicine_and_rehabilitation",
	},
	{
		enName: "Internal Medicine",
		frName: "Medecine Interne",
		arName: "الطب الباطني",
		slug: "internal_medicine",
	},
	{
		enName: "Infectious Diseases",
		frName: "Maladies Infectieuses",
		arName: "الأمراض المعدية",
		slug: "infectious_diseases",
	},
	{
		enName: "Hematology",
		frName: "Hematologie",
		arName: "أمراض الدم",
		slug: "hematology",
	},
	{
		enName: "Obstetrics and Gynecology",
		frName: "Gynecologie-obstetrique",
		arName: "طب النساء والتوليد",
		slug: "obstetrics_and_gynecology",
	},
	{
		enName: "Gastroenterology",
		frName: "Gastrologie",
		arName: "طب الجهاز الهضمي",
		slug: "gastroenterology",
	},
	{
		enName: "Endocrinology",
		frName: "Endocrinologie",
		arName: "طب الغدد الصماء",
		slug: "endocrinology",
	},
	{
		enName: "Dermatology",
		frName: "Dermatologie",
		arName: "الأمراض الجلدية",
		slug: "dermatology",
	},
	{
		enName: "Plastic Surgery",
		frName: "Chirurgie Plastique",
		arName: "جراحة التجميل",
		slug: "plastic_surgery",
	},
	{
		enName: "Orthopedic Surgery",
		frName: "Chirurgie Orthopedique",
		arName: "جراحة العظام",
		slug: "orthopedic_surgery",
	},
	{
		enName: "Maxillofacial Surgery",
		frName: "Chirurgie Maxillo-faciale",
		arName: "جراحة الوجه والفكين",
		slug: "maxillofacial_surgery",
	},
	{
		enName: "Pediatric Surgery",
		frName: "Chirurgie Infantile",
		arName: "جراحة الأطفال",
		slug: "pediatric_surgery",
	},
	{
		enName: "General Surgery",
		frName: "Chirurgie Generale",
		arName: "الجراحة العامة",
		slug: "general_surgery",
	},
	{
		enName: "Cardiovascular and Thoracic Surgery",
		frName: "Chi. Cardiovasculaire T",
		arName: "جراحة القلب والأوعية الدموية والصدر",
		slug: "cardiovascular_and_thoracic_surgery",
	},
	{
		enName: "Cardiology",
		frName: "Cardiologie",
		arName: "أمراض القلب",
		slug: "cardiology",
	},
	{
		enName: "Physiotherapy & Kinesitherapy",
		frName: "Physiotherapie et kinesitherapie",
		arName: "العلاج الطبيعي والحركات العلاجية",
		slug: "physiotherapy",
	},
	{
		enName: "Psychology",
		frName: "Psychologie",
		arName: "علم النفس",
		slug: "psychology",
	},
	{
		enName: "Allergology",
		frName: "Allergologie",
		arName: "أمراض الحساسية",
		slug: "allergology",
	},
	{
		enName: "Vascular Medicine & Angiology",
		frName: "Medecine vasculaire et angiologie",
		arName: "طب الأوعية الدموية",
		slug: "vascular_medicine",
	},
	{
		enName: "Diabetology",
		frName: "Diabetologie",
		arName: "طب السكري",
		slug: "diabetology",
	},
];
